// Generated by scripts/process-images.mjs. Do not edit by hand.

export const images = {
  "home-hero": {
    width: 1040,
    height: 780,
    retinaWidth: 1364
  },
  "home-new-england": {
    width: 1200,
    height: 800,
    retinaWidth: 1535
  },
  "areas-agent-call": {
    width: 1600,
    height: 900,
    retinaWidth: null
  },
  "plan-hmo": {
    width: 1200,
    height: 675,
    retinaWidth: null
  },
  "plan-ppo": {
    width: 1200,
    height: 675,
    retinaWidth: null
  },
  "plan-pffs": {
    width: 1200,
    height: 675,
    retinaWidth: null
  },
  "plan-msa": {
    width: 1200,
    height: 675,
    retinaWidth: null
  },
  "plan-snp": {
    width: 1200,
    height: 675,
    retinaWidth: null
  },
  veterans: {
    width: 1200,
    height: 675,
    retinaWidth: null
  },
  "turning-65": {
    width: 1200,
    height: 675,
    retinaWidth: null
  },
  "employer-retirement": {
    width: 1200,
    height: 675,
    retinaWidth: null
  },
  "contact-office": {
    width: 1200,
    height: 800,
    retinaWidth: null
  },
  "events-seminar": {
    width: 1200,
    height: 675,
    retinaWidth: null
  },
  articles: {
    width: 1200,
    height: 675,
    retinaWidth: null
  }
} as const;

export type ImageName = keyof typeof images;
